<?php
$refranero = [
    "Más vale estar solo que mal acompañado",
    "Perro ladrador poco mordedor",
    "A caballo regalado no le mires el dentado",
    "A lo hecho, pecho.",
    "Al mal tiempo, buena cara.",
    "Cada loco con su tema.",
    "De tal palo, tal astilla.",
    "El que la hace, la paga.",
    "Dinero llama dinero.",
    "El mundo es un pañuelo.",
    "Cada oveja con su pareja.",
    "Más vale prevenir que lamentar.",
    "Más vale tarde que nunca.",
    "En boca cerrada no entran moscas.",
    "Al que madruga, Dios lo ayuda.",
    "A la tercera va la vencida.",
    "El que calla otorga.",
    "Amor con hambre no dura.",
    "Tira la piedra y esconde la mano.",
    "El hábito no hace al monje.",
    "A palabras necias, oídos sordos.",
    "Crea fama y acuéstate a dormir.",
    "Del dicho al hecho, hay mucho trecho.",
    "Dios aprieta pero no ahorca.",
    "El que ríe el último, ríe mejor.",
    "Donde fueres, haz lo que vieres.",
    "Quien mucho abarca, poco aprieta.",
    "Hombre precavido vale por dos.",
    "Preguntando se llega a Roma.",
    "Zapatero a sus zapatos.",
    "Una golondrina no hace verano.",
    "Obras son amores y no buenas razones.",
    "Mucho ruido y pocas nueces.",
    "En la variedad está el gusto.",
    "Tanto tienes, tanto vales.",
    "Nadie es profeta en su tierra.",
    "¿Dónde va Vicente? Donde va la gente.",
    "Dios los cría y ellos se juntan.",
    "El que espera desespera.",
    "Escoba nueva barre bien.",
    "No hay mal que dure cien años.",
    "Guerra avisada no mata soldados.",
    "La fe mueve montañas.",
    "El que no la debe, no la teme.",
    "Perro que ladra, no muerde.",
    "Si te he visto, no me acuerdo.",
    "No hay mal que por bien no venga.",
    "Si así llueve, que no escampe.",
    "Querer es poder.",
    "Loro viejo no aprende a hablar.",
    "Más vale maña que fuerza.",
    "El papel aguanta todo.",
    "Barriga llena, corazón contento.",
    "Casa de herrero, cuchillo de palo.",
    "Poco a poco se anda lejos.",
    "Malos ojos son cariño.",
    "Lo cortés no quita lo valiente.",
    "A otro perro con ese hueso.",
    "Contigo pan y cebolla.",
    "Jaula nueva, pájaro muerto.",
    "Nunca es tarde si la dicha es buena.",
    "Sarna con gusto no pica.",
    "Quien tiene boca se equivoca.",
    "El poeta nace, no se hace.",
    "Haz bien y no mires a quien.",
    "El que se excusa, se acusa.",
    "El pez grande se come al chico.",
    "Lo barato sale caro.",
    "Para muestra, un botón.",
    "Se dice el pecado, más no el pecador.",
    "Mucho donaire, causa desaire.",
    "Hoy por ti, mañana por mí.",
    "No hay rosa sin espinas.",
    "El que busca, encuentra.",
    "Quien se pica, ajos come.",
    "Gota a gota, la mar se agota.",
    "Hierba mala nunca muere.",
    "El tiempo es oro.",
    "Ojo por ojo, diente por diente.",
    "Quien canta, su mal espanta.",
    "Del árbol caído, todos hacen leña.",
    "El que a hierro mata, a hierro muere.",
    "Piensa mal y acertarás.",
    "Por la boca muere el pez.",
    "Ojos que no ven, corazón que no siente.",
    "La excepción hace la regla.",
    "Como se vive, se muere.",
    "Un clavo saca otro clavo.",
    "Mañana será otro día.",
    "Decir refranes, es decir verdades.",
    "No hay quinto malo.",
    "La intención es lo que cuenta.",
    "La música amansa las fieras.",
    "Más claro no canta un gallo.",
    "El casado, casa quiere.",
    "A mala vida, mala muerte.",
    "Caras vemos, corazones no sabemos.",
    "Al pan, pan, y al vino, vino.",
    "Cría cuervos y te sacarán los ojos.",
];

$refrarandom = rand(0, count($refranero) - 1);
echo $refranero[$refrarandom];
