version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: viajes
      LC_COLLATE: 'es_ES.utf8'
      LC_CTYPE: 'es_ES.utf8'
    networks:
      - default
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "5050:80"
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db
    networks:
      - default
